#!/usr/bin/env bash
set -xe

source_region=eu-central-1
system=$(nix eval --raw nixpkgs#system)

AMIS_FILE=../amis.json
NEW_AMIS=$(mktemp)
printf "{}" > $NEW_AMIS

for release in "stable" "unstable"; do 
    ami_path="ami-$release-$system"

    nix build ".#ami-$release" --out-link $ami_path

    aws s3 sync \
        --region $source_region \
        --no-progress \
        --exclude "*" --include "*.vhd" \
        --metadata "Release=$release,System=$system" \
        $ami_path \
        "s3://cachix-deploy-amis/$ami_path/"
done

terraform state mv aws_s3_bucket.cachix-deploy-amis aws_s3_bucket.cachix_deploy_amis
terraform apply -target="data.aws_s3_objects.cachix_deploy_vhds" -input=false -no-color -auto-approve
terraform apply -input=false -no-color -auto-approve
# terraform plan -input=false -no-color

ami_ids=$(terraform output -json ami-id)
echo $ami_ids

    # regions=$(aws --region $source_region ec2 describe-regions --query 'Regions[].{Name:RegionName}' --output text)
    # for region in $regions; do
    #    aws ec2 copy-image \
    #         --source-region $source_region \
    #         --source-image-id $ami_id \
    #         --region $region \
    #         --name cachix-deploy \
    #      | jq --arg ami_name "$release.$region.$system" \
    #           --slurp \
    #           '.[1][($ami_name)] = .[0].ImageId | .[1]' - $NEW_AMIS \
    #      | sponge $NEW_AMIS

cp $NEW_AMIS "amis-$system.json"
